package com.bgroceries.backend.entity.Stocks;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * A supplier (Stocks → Products → Suppliers) — farms, producers and
 * wholesalers that B'Groceries buys stock from, with contact details and the
 * purchasing terms agreed with them. {@code code} follows the SP-####
 * sequence and is auto-generated by the service when omitted. Products still
 * reference suppliers by name string until they are upgraded to foreign keys,
 * same as category/brand/unit.
 */
@Entity
@Table(name = "supplier")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Supplier {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique business code (e.g. SP-0001); auto-generated when not provided. */
    @Column(name = "code", length = 50, unique = true)
    private String code;

    /** Supplier business/contact name. */
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /** Second-language (Khmer) display text. */
    @Column(name = "name_kh", length = 200)
    private String nameKh;

    /** Supplier group this vendor belongs to (Stocks → Suppliers Group). */
    @Column(name = "supplier_group", length = 200)
    private String supplierGroup;

    /** Tax number (VAT/TIN) registered with the supplier. */
    @Column(name = "tax_number", length = 100)
    private String taxNumber;

    /** Payment term, e.g. NET-30 or COD. */
    @Column(name = "payment_term", length = 100)
    private String paymentTerm;

    /** Default purchase-order template used when buying from this supplier. */
    @Column(name = "po_template_name", length = 200)
    private String poTemplateName;

    /** Preferred shipment method, e.g. Road / Air / Sea. */
    @Column(name = "shipment_method", length = 200)
    private String shipmentMethod;

    /** Purchasing person in charge of this supplier. */
    @Column(name = "purchase_person", length = 200)
    private String purchasePerson;

    /** Agreed terms and conditions for purchases from this supplier. */
    @Column(name = "term_condition", length = 200)
    private String termCondition;

    /** Default bill template used when recording this supplier's bills. */
    @Column(name = "bill_template_name", length = 200)
    private String billTemplateName;

    /** Running balance owed to/by this supplier (column predates the 2026-08 rewrite). */
    @Column(name = "current_balance", precision = 18, scale = 2)
    private java.math.BigDecimal currentBalance;

    /** Debit / deposit payment term agreed with this supplier (legacy column). */
    @Column(name = "debit_deposit_payment_term", length = 100)
    private String debitDepositPaymentTerm;

    // ---- Default contact (Contact Information section) -------------------
    // Stored flat until dedicated contact/address tables exist — the modal's
    // sub-tables persist their first/default row into these columns.

    @Column(name = "contact_first_name", length = 100)
    private String contactFirstName;

    @Column(name = "contact_last_name", length = 100)
    private String contactLastName;

    /** Male / Female / Other. */
    @Column(name = "contact_gender", length = 20)
    private String contactGender;

    @Column(name = "contact_dob")
    private java.time.LocalDate contactDob;

    @Column(name = "contact_phone", length = 50)
    private String contactPhone;

    @Column(name = "contact_mobile", length = 50)
    private String contactMobile;

    @Column(name = "contact_email", length = 200)
    private String contactEmail;

    @Column(name = "contact_website", length = 200)
    private String contactWebsite;

    // ---- Default address (Location Information section) ------------------

    @Column(name = "address_description", length = 200)
    private String addressDescription;

    @Column(name = "address_name_kh", length = 200)
    private String addressNameKh;

    @Column(name = "address_line1", length = 300)
    private String addressLine1;

    @Column(name = "address_line2", length = 300)
    private String addressLine2;

    @Column(name = "address_city", length = 100)
    private String addressCity;

    @Column(name = "address_state", length = 100)
    private String addressState;

    @Column(name = "address_country", length = 100)
    private String addressCountry;

    @Column(name = "address_phone", length = 50)
    private String addressPhone;

    @Column(name = "address_phone_ext", length = 20)
    private String addressPhoneExt;

    @Column(name = "address_fax", length = 50)
    private String addressFax;

    @Column(name = "address_fax_ext", length = 20)
    private String addressFaxExt;

    @Column(name = "address_email", length = 200)
    private String addressEmail;

    @Column(name = "address_website", length = 200)
    private String addressWebsite;

    @Builder.Default
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.active == null) this.active = true;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
