package com.bgroceries.backend.entity.Stocks;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * A supplier group (Stocks → Products → Suppliers Group) that organizes
 * suppliers into regional or category groups. {@code code} follows the
 * SG-#### sequence and is auto-generated by the service when omitted.
 * Suppliers still reference groups by name string until they are upgraded to
 * foreign keys, same as category/brand/unit.
 */
@Entity
@Table(name = "supplier_group")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SupplierGroup {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique business code (e.g. SG-0001); auto-generated when not provided. */
    @Column(name = "code", length = 50, unique = true)
    private String code;

    @Column(name = "description", nullable = false, length = 200)
    private String description;

    /** Second-language (Khmer) display text. */
    @Column(name = "name_kh", length = 200)
    private String nameKh;

    @Builder.Default
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.active == null) this.active = true;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
