package com.bgroceries.backend.entity.Stocks;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * A unit of measure (Stocks → Products → Unit of Measure) such as kg, g, L,
 * ml or piece. {@code code} follows the UN-#### sequence and is
 * auto-generated by the service when omitted. {@code factor} is the
 * conversion factor relative to the base unit of its dimension (e.g.
 * gram = 1, kilogram = 1000). Products still reference units by name string
 * until they are upgraded to foreign keys, same as category/brand/supplier.
 */
@Entity
@Table(name = "unit_of_measure")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UnitOfMeasure {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique business code (e.g. UN-0001); auto-generated when not provided. */
    @Column(name = "code", length = 50, unique = true)
    private String code;

    @Column(name = "description", nullable = false, length = 200)
    private String description;

    /** Second-language (Khmer) display text. */
    @Column(name = "name_kh", length = 200)
    private String nameKh;

    /**
     * Conversion factor relative to the base unit of its dimension
     * (e.g. gram = 1, kilogram = 1000). Null means no conversion defined yet.
     */
    @Column(name = "factor")
    private Double factor;

    @Builder.Default
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.active == null) this.active = true;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
