package com.bgroceries.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * A product attribute definition (Stocks → Products → Attribute) such as
 * Size, Color or Flavor, with the allowed values as a comma-separated string
 * ("Small, Medium, Large"). {@code code} follows the AT-#### sequence and is
 * auto-generated by the service when omitted — same flow as Category.
 */
@Entity
@Table(name = "attribute")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Attribute {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique business code (e.g. AT-0001); auto-generated when not provided. */
    @Column(name = "code", length = 50, unique = true)
    private String code;

    /** Primary (English) attribute name, e.g. "Color". */
    @Column(name = "description", nullable = false, length = 200)
    private String description;

    /** Second-language (Khmer) display text. */
    @Column(name = "name_kh", length = 200)
    private String nameKh;

    /** Free-text type tag: Text / Number / Color / Size / Flavor… */
    @Column(name = "type", length = 50)
    private String type;

    /** Comma-separated allowed values, e.g. "Small, Medium, Large". */
    @Column(name = "values_text", length = 1000)
    private String values;

    @Builder.Default
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.active == null) this.active = true;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
